import { strict } from "assert";
import * as z from "zod";
import { BatchStatus, DiscountType, Gender, StudentStatus, TeacherStatus } from "./type";

// Course Schema
export const CreateCourseSchema = z.object({
  title: z.string(),
  duration: z.number(),
  descriptionInDetail: z.string(),
  descriptionInShort: z.string(),
  imageForThumbnail: z.string(),
  roadmap: z.string(),
  totalFees: z.number(),
  offeredFees: z.number(),
  instractionMode: z.string(),
});
export type CreateCourseFormValues = z.infer<typeof CreateCourseSchema>;
 

// Course Update Schema
export const UpdateCourseSchema = z.object({
  id: z.string(),
  title: z.string(),
  duration: z.number(),
  descriptionInDetail: z.string(),
  descriptionInShort: z.string(),
  imageForThumbnail: z.string(),
  roadmap: z.string(),
  totalFees: z.number(),
  offeredFees: z.number(),
  instractionMode: z.string(),
});
export type UpdateCourseFormValues = z.infer<typeof UpdateCourseSchema>;







// Teachers Schema
export const CreateTeacherSchema = z.object({
  name: z.string().min(2, "Teacher name is required"),
  code: z.string().min(2, "Teacher code is required"),
  phone: z.string().min(10, "Phone is required"),
  alternatePhone: z.string().optional().or(z.literal("")),
  email: z.string().email("Invalid email"),
  professionalEmail: z.string().optional().or(z.literal("")),
  qualification: z.string().min(2, "Qualification is required"),
  salaryAmount: z.coerce.number().min(1, "Salary amount is required"),
  joiningDate: z.string().min(1, "Joining date is required"),
  status: z.nativeEnum(TeacherStatus),
});

export type CreateTeacherFormInput = z.input<typeof CreateTeacherSchema>;
export type CreateTeacherFormValues = z.output<typeof CreateTeacherSchema>;


// Update teacher schema
export const UpdateTeacherSchema = z.object({
  id: z.string(),
  name: z.string().min(2, "Teacher name is required"),
  code: z.string().min(2, "Teacher code is required"),
  phone: z.string().min(10, "Phone is required"),
  alternatePhone: z.string().optional().or(z.literal("")),
  email: z.string().email("Invalid email"),
  professionalEmail: z.string().optional().or(z.literal("")),
  qualification: z.string().min(2, "Qualification is required"),
  salaryAmount: z.number().min(1, "Salary is required"),
  joiningDate: z.string().min(1, "Joining date is required"),
  status: z.nativeEnum(TeacherStatus),
});

export type UpdateTeacherFormValues = z.infer<typeof UpdateTeacherSchema>;







// Batch Schema
export const CreateBatchSchema = z.object({
  name: z.string().min(2, "Batch name is required"),
  capacity: z.number().min(1, "Capacity must be at least 1"),
  startDate: z.string().min(1, "Start date is required"),
  endDate: z.string().min(1, "End date is required"),
  scheduleTime: z.string().min(1, "Schedule time is required"),
  roomNo: z.string().optional().or(z.literal("")),
  batchCode: z.string().min(2, "Batch code is required"),
  courseId: z.string().min(1, "Course is required"),
  teacherId: z.string().min(1, "Teacher is required"),
  status: z.nativeEnum(BatchStatus),
});

export type CreateBatchFormValues = z.infer<typeof CreateBatchSchema>;

export const UpdateBatchSchema = z.object({
  id: z.string(),
  name: z.string().min(2, "Batch name is required"),
  capacity: z.number().min(1, "Capacity must be at least 1"),
  startDate: z.string().min(1, "Start date is required"),
  endDate: z.string().min(1, "End date is required"),
  scheduleTime: z.string().min(1, "Schedule time is required"),
  roomNo: z.string().optional().or(z.literal("")),
  batchCode: z.string().min(2, "Batch code is required"),
  courseId: z.string().min(1, "Course is required"),
  teacherId: z.string().min(1, "Teacher is required"),
  status: z.nativeEnum(BatchStatus),
});

export type UpdateBatchFormValues = z.infer<typeof UpdateBatchSchema>;






// Create Certificate Schema
export const CreateCertificateSchema = z.object({
  certificateNumber: z.string().min(1, "Certificate number is required"),
  verificationHash: z.string().min(1, "Verification hash is required"),

  studentId: z.string().min(1, "Student is required"),
  courseId: z.string().min(1, "Course is required"),
  enrollmentId: z.string().min(1, "Enrollment is required"),
  batchId: z.string().min(1, "Batch is required"),
  templateId: z.string().min(1, "Template is required"),

  issueDate: z.string().min(1, "Issue date is required"),
  completionDate: z.string().min(1, "Completion date is required"),

  grade: z.string().min(1, "Grade is required"),

  remarks: z.string().optional().or(z.literal("")),
  revokedReason: z.string().optional().or(z.literal("")),
  revokedAt: z.string().optional().or(z.literal("")),

  generatedBy: z.string().min(1, "Generated by is required"),
  pdfUrl: z.string().optional().or(z.literal("")),

  isActive: z.boolean(),
});

export type CreateCertificateFormValues = z.infer<typeof CreateCertificateSchema>;

// Update Certificate Schema
export const UpdateCertificateSchema = z.object({
  id: z.string(),

  certificateNumber: z.string().min(1, "Certificate number is required"),
  verificationHash: z.string().min(1, "Verification hash is required"),

  studentId: z.string().min(1, "Student is required"),
  courseId: z.string().min(1, "Course is required"),
  enrollmentId: z.string().min(1, "Enrollment is required"),
  batchId: z.string().min(1, "Batch is required"),
  templateId: z.string().min(1, "Template is required"),

  issueDate: z.string().min(1, "Issue date is required"),
  completionDate: z.string().min(1, "Completion date is required"),

  grade: z.string().min(1, "Grade is required"),

  remarks: z.string().optional().or(z.literal("")),
  revokedReason: z.string().optional().or(z.literal("")),
  revokedAt: z.string().optional().or(z.literal("")),

  generatedBy: z.string().min(1, "Generated by is required"),
  pdfUrl: z.string().optional().or(z.literal("")),

  isActive: z.boolean(),
});

export type UpdateCertificateFormValues = z.infer<typeof UpdateCertificateSchema>;





// 🔹 Create Student Schema
export const CreateStudentSchema = z.object({
  name: z.string().min(1, "Name is required"),
  gender: z.nativeEnum(Gender),

  address: z.string().min(1, "Address is required"),
  collegeName: z.string().min(1, "College name is required"),
  branchName: z.string().min(1, "Branch name is required"),

  DOB: z.string().min(1, "Date of birth is required"),

  mobile: z.string().min(10, "Mobile number must be valid"),
  alternateMobile: z.string().optional().or(z.literal("")),

  email: z.string().email("Invalid email"),

  fatherName: z.string().optional().or(z.literal("")),
  fatherContact: z.string().optional().or(z.literal("")),
  fatherOccupation: z.string().optional().or(z.literal("")),

  motherName: z.string().optional().or(z.literal("")),
  motherContact: z.string().optional().or(z.literal("")),
  motherOccupation: z.string().optional().or(z.literal("")),

  admissionDate: z.string().min(1, "Admission date is required"),

  status: z.nativeEnum(StudentStatus),

  batchId: z.string().min(1, "Batch is required"),
});

export type CreateStudentFormValues = z.infer<typeof CreateStudentSchema>;


// 🔹 Update Student Schema
export const UpdateStudentSchema = z.object({
  id: z.string(),

  name: z.string().min(1, "Name is required"),
  gender: z.nativeEnum(Gender),

  address: z.string().min(1, "Address is required"),
  collegeName: z.string().min(1, "College name is required"),
  branchName: z.string().min(1, "Branch name is required"),

  DOB: z.string().min(1, "Date of birth is required"),

  mobile: z.string().min(10, "Mobile number must be valid"),
  alternateMobile: z.string().optional().or(z.literal("")),

  email: z.string().email("Invalid email"),

  fatherName: z.string().optional().or(z.literal("")),
  fatherContact: z.string().optional().or(z.literal("")),
  fatherOccupation: z.string().optional().or(z.literal("")),

  motherName: z.string().optional().or(z.literal("")),
  motherContact: z.string().optional().or(z.literal("")),
  motherOccupation: z.string().optional().or(z.literal("")),

  admissionDate: z.string().min(1, "Admission date is required"),

  status: z.nativeEnum(StudentStatus),

  batchId: z.string().min(1, "Batch is required"),
});

export type UpdateStudentFormValues = z.infer<typeof UpdateStudentSchema>;











export const CreateFeeStructureSchema = z.object({
  courseTotalFee: z.coerce.number().min(0, "Course total fee is required"),

  discountType: z.nativeEnum(DiscountType).optional(),
  discountValue: z.coerce.number().optional(),
  discountAmount: z.coerce.number().optional(),

  finalFee: z.coerce.number().min(0, "Final fee is required"),

  emiOption: z.boolean(),

  enrollmentId: z.string().min(1, "Enrollment ID is required"),
  studentId: z.string().min(1, "Student ID is required"),

  isActive: z.boolean(),
});

export type CreateFeeStructureFormValues = z.infer<
  typeof CreateFeeStructureSchema
>;

export const UpdateFeeStructureSchema = z.object({
  id: z.string(),

  courseTotalFee: z.coerce.number().min(0, "Course total fee is required"),

  discountType: z.nativeEnum(DiscountType).optional(),
  discountValue: z.coerce.number().optional(),
  discountAmount: z.coerce.number().optional(),

  finalFee: z.coerce.number().min(0, "Final fee is required"),

  emiOption: z.boolean(),

  enrollmentId: z.string().min(1, "Enrollment ID is required"),
  studentId: z.string().min(1, "Student ID is required"),

  isActive: z.boolean(),
});

export type UpdateFeeStructureFormValues = z.infer<
  typeof UpdateFeeStructureSchema
>;